### ISSUE TITLE
Flag placement issue

### ISSUE THREAD

**Issue by Valakii0** [aadrian2006/aadrian2006.github.io#2]
You can put flags on already cleared tiles, and removes the number, please fix!

**Comment by 6Leoo6** [comment]
I've already fixed the issue, but the lazy owner of the repo is unable to press a single button to merge my pull request! I'm thinking about forking this repo and continuing development under my own supervision.

**Comment by 6Leoo6** [comment]
He merged it finally!!! You can now close this issue!!! 👑

**Comment by Valakii0** [comment]
what issue?

**Comment by Valakii0** [comment]
i dont see any
